run:
  timeout: 5m
  tests: true
  go: '1.21'
output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - prealloc
    - bodyclose
    - nilerr
    - errname
    - unconvert
    - unparam
    - whitespace
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Tx).Rollback
      - (*github.com/jmoiron/sqlx.Tx).Rollback
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: blank-imports
        disabled: true
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: var-naming
      - name: var-declaration
  goimports:
    local-prefixes: Avito
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
    - testdata
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - errcheck
      text: "Error return value of `.*\\.Close` is not checked"
    - linters:
        - errcheck
      text: "Error return value of `.*Rollback` is not checked"
    - path: internal/service
      linters:
        - gosec
      text: "G404"
